#pragma once

#define POKEMON_NAME_LENGTH 10

#define SPECIES_NONE 0x0
#define SPECIES_BULBORBLARVA 0x1
#define SPECIES_BULBORB 0x2
#define SPECIES_JUMBOBULBORB 0x3
#define SPECIES_FIERYBLOWLET 0x4
#define SPECIES_FIERYBLOWHOG 0x5
#define SPECIES_TITANBLOWHOG 0x6
#define SPECIES_WOLPOLE 0x7
#define SPECIES_YELLOWWOLLYHOP 0x8
#define SPECIES_MASTERHOP 0x9
#define SPECIES_FLINTBEETLE 0xA
#define SPECIES_DOODLEBUG 0xB
#define SPECIES_GLINTBEETLE 0xC
#define SPECIES_SWOOPINGSNITCHBUG 0xD
#define SPECIES_BUMBLINGSNITCHBUG 0xE
#define SPECIES_DIRIGIBUG 0xF
#define SPECIES_SNOWBULBORB 0x10
#define SPECIES_DWARFFROSTYBULBORB 0x11
#define SPECIES_FROSTYBULBORB 0x12
#define SPECIES_CRUMBUG 0x13
#define SPECIES_BREADBUG 0x14
#define SPECIES_GIANTBREADBUG 0x15
#define SPECIES_FEAROW 0x16 // To be replaced (?)
#define SPECIES_EKANS 0x17 // To be replaced (?)
#define SPECIES_DWARFBULBEAR 0x18
#define SPECIES_SPOTTYBULBEAR 0x19
#define SPECIES_HONEYWISP 0x1A
#define SPECIES_DANDELFLY 0x1B
#define SPECIES_DOWNYSNAGRET 0x1C
#define SPECIES_BURROWINGSNAGRET 0x1D
#define SPECIES_PILEATEDSNAGRET 0x1E
#define SPECIES_FEMALESHEARGRUB 0x1F
#define SPECIES_SWARMINGSHEARGRUB 0x20
#define SPECIES_MAMASHEARGRUB 0x21
#define SPECIES_MALESHEARGRUB 0x22
#define SPECIES_SHEARWIG 0x23
#define SPECIES_QUEENSHEARWIG 0x24
#define SPECIES_ARISTOCRABOFFSPRING 0x25
#define SPECIES_ARISTOCRAB 0x26
#define SPECIES_GOOLIX 0x27
#define SPECIES_FOOLIX 0x28
#define SPECIES_ARCTICCANNONLARVA 0x29
#define SPECIES_ARCTICCANNONBEETLE 0x2A
#define SPECIES_SKITTERLEAF 0x2B
#define SPECIES_DESICCATEDSKITTERLEAF 0x2C
#define SPECIES_ARMOREDCANNONLARVA 0x2D
#define SPECIES_ARMOREDCANNONBEETLE 0x2E
#define SPECIES_HORNEDCANNONBEETLE 0x2F
#define SPECIES_CREEPINGCHRYSANTHEMUM 0x30
#define SPECIES_STARTLESPORE 0x31
#define SPECIES_HERMITCRAWMAD 0x32
#define SPECIES_BUGEYEDCRAWMAD 0x33
#define SPECIES_DWARFBULBORB 0x34
#define SPECIES_DWARFORANGEBULBORB 0x35
#define SPECIES_BEADYLONGLEGS 0x36
#define SPECIES_RAGINGLONGLEGS 0x37
#define SPECIES_BALDYLONGLEGS 0x38
#define SPECIES_SHAGGYLONGLEGS 0x39
#define SPECIES_BULBMIN 0x3A
#define SPECIES_ADULTBULBMIN 0x3B
#define SPECIES_SCORNET 0x3C
#define SPECIES_POLIWHIRL 0x3D // To be replaced (?)
#define SPECIES_BURROWNIT 0x3E
#define SPECIES_ABRA 0x3F // To be replaced (?)
#define SPECIES_KADABRA 0x40 // To be replaced (?)
#define SPECIES_VOLATILEDWEEVIL 0x41
#define SPECIES_MANATLEGS 0x42
#define SPECIES_MACHOKE 0x43 // To be replaced (?)
#define SPECIES_MACHAMP 0x44 // To be replaced (?)
#define SPECIES_ARACHNODE 0x45
#define SPECIES_MOLDYDWARFBULBORB 0x46
#define SPECIES_MOLDYSLOOCH 0x47
#define SPECIES_TOXSTOOL 0x48
#define SPECIES_PHOSBAT 0x49
#define SPECIES_VEHEAMOTHPHOSBAT 0x4A
#define SPECIES_PUCKERINGBLINNOW 0x4B
#define SPECIES_SPUTTLEFISH 0x4C
#define SPECIES_PRICKLEPUFF 0x4D
#define SPECIES_RAPIDASH 0x4E // To be replaced (?)
#define SPECIES_SLOWPOKE 0x4F // To be replaced (?)
#define SPECIES_SLOWBRO 0x50 // To be replaced (?)
#define SPECIES_PUFFYBLOWHOG 0x51
#define SPECIES_MAGNETON 0x52 // To be replaced (?)
#define SPECIES_FARFETCHD 0x53 // To be replaced (?)
#define SPECIES_PYROCLASTICSLOOCH 0x54
#define SPECIES_LESSERSPOTTEDJELLYFLOAT 0x55
#define SPECIES_GREATERSPOTTEDJELLYFLOAT 0x56
#define SPECIES_DEWGONG 0x57 // To be replaced (?)
#define SPECIES_GRIMER 0x58 // To be replaced (?)
#define SPECIES_SNOWYBLOWHOG 0x59
#define SPECIES_BLIZZARDINGBLOWHOG 0x5A
#define SPECIES_CLOYSTER 0x5B // To be replaced (?)
#define SPECIES_GASTLY 0x5C // To be replaced (?)
#define SPECIES_HAUNTER 0x5D // To be replaced (?)
#define SPECIES_GENGAR 0x5E // To be replaced (?)
#define SPECIES_ONIX 0x5F // To be replaced (?)
#define SPECIES_SUNQUISH 0x60
#define SPECIES_PROQUILLION 0x61
#define SPECIES_KRABBY 0x62 // To be replaced (?)
#define SPECIES_SNOWFLAKEFLUTTERTAIL 0x63
#define SPECIES_BOGSWALLOW 0x64
#define SPECIES_PUFFMIN 0x65
#define SPECIES_WOLLYHOP 0x66
#define SPECIES_EXEGGUTOR 0x67 // To be replaced (?)
#define SPECIES_CUBONE 0x68 // To be replaced (?)
#define SPECIES_SCORCHCAKE 0x69
#define SPECIES_WATERDUMPLE 0x6A
#define SPECIES_LONGWATERDUMPLE 0x6B
#define SPECIES_MOCKIWI 0x6C
#define SPECIES_KOFFING 0x6D // To be replaced (?)
#define SPECIES_WEEZING 0x6E // To be replaced (?)
#define SPECIES_RHYHORN 0x6F // To be replaced (?)
#define SPECIES_RHYDON 0x70 // To be replaced (?)
#define SPECIES_CHANSEY 0x71 // To be replaced (?)
#define SPECIES_TANGELA 0x72 // To be replaced (?)
#define SPECIES_KANGASKHAN 0x73 // To be replaced (?)
#define SPECIES_HORSEA 0x74 // To be replaced (?)
#define SPECIES_SEADRA 0x75 // To be replaced (?)
#define SPECIES_GOLDEEN 0x76 // To be replaced (?)
#define SPECIES_BEARDEDAMPRAT 0x77
#define SPECIES_STARYU 0x78 // To be replaced (?)
#define SPECIES_GATTLINGGROINK 0x79
#define SPECIES_MR_MIME 0x7A // To be replaced (?)
#define SPECIES_SCYTHER 0x7B // To be replaced (?)
#define SPECIES_ARMOREDMAWDAD 0x7C
#define SPECIES_ELECTABUZZ 0x7D // To be replaced (?)
#define SPECIES_MAGMAR 0x7E // To be replaced (?)
#define SPECIES_PINSIR 0x7F // To be replaced (?)
#define SPECIES_TAUROS 0x80 // To be replaced (?)
#define SPECIES_PELLETPOSY 0x81
#define SPECIES_MASTERONION 0x82
#define SPECIES_OATCHI 0x83
#define SPECIES_QUAGGLEDMIRECLOPS 0x84
#define SPECIES_EEVEE 0x85
#define SPECIES_VAPOREON 0x86
#define SPECIES_JOLTEON 0x87
#define SPECIES_FLAREON 0x88
#define SPECIES_PORYGON 0x89
#define SPECIES_OMANYTE 0x8A
#define SPECIES_OMASTAR 0x8B
#define SPECIES_KABUTO 0x8C
#define SPECIES_KABUTOPS 0x8D
#define SPECIES_AERODACTYL 0x8E
#define SPECIES_SNORLAX 0x8F
#define SPECIES_ARTICUNO 0x90
#define SPECIES_ZAPDOS 0x91
#define SPECIES_MOLTRES 0x92
#define SPECIES_DRATINI 0x93
#define SPECIES_DRAGONAIR 0x94
#define SPECIES_DRAGONITE 0x95
#define SPECIES_MEWTWO 0x96
#define SPECIES_MEW 0x97
#define SPECIES_CHIKORITA 0x98
#define SPECIES_BAYLEEF 0x99
#define SPECIES_MEGANIUM 0x9A
#define SPECIES_CYNDAQUIL 0x9B
#define SPECIES_QUILAVA 0x9C
#define SPECIES_TYPHLOSION 0x9D
#define SPECIES_TOTODILE 0x9E
#define SPECIES_CROCONAW 0x9F
#define SPECIES_FERALIGATR 0xA0
#define SPECIES_SENTRET 0xA1
#define SPECIES_FURRET 0xA2
#define SPECIES_HOOTHOOT 0xA3
#define SPECIES_NOCTOWL 0xA4
#define SPECIES_LEDYBA 0xA5
#define SPECIES_LEDIAN 0xA6
#define SPECIES_SPINARAK 0xA7
#define SPECIES_ARIADOS 0xA8
#define SPECIES_CROBAT 0xA9
#define SPECIES_CHINCHOU 0xAA
#define SPECIES_LANTURN 0xAB
#define SPECIES_PICHU 0xAC
#define SPECIES_CLEFFA 0xAD
#define SPECIES_IGGLYBUFF 0xAE
#define SPECIES_TOGEPI 0xAF
#define SPECIES_TOGETIC 0xB0
#define SPECIES_NATU 0xB1
#define SPECIES_XATU 0xB2
#define SPECIES_MAREEP 0xB3
#define SPECIES_FLAAFFY 0xB4
#define SPECIES_AMPHAROS 0xB5
#define SPECIES_BELLOSSOM 0xB6
#define SPECIES_MARILL 0xB7
#define SPECIES_AZUMARILL 0xB8
#define SPECIES_SUDOWOODO 0xB9
#define SPECIES_POLITOED 0xBA
#define SPECIES_HOPPIP 0xBB
#define SPECIES_SKIPLOOM 0xBC
#define SPECIES_JUMPLUFF 0xBD
#define SPECIES_AIPOM 0xBE
#define SPECIES_SUNKERN 0xBF
#define SPECIES_SUNFLORA 0xC0
#define SPECIES_YANMA 0xC1
#define SPECIES_WOOPER 0xC2
#define SPECIES_QUAGSIRE 0xC3
#define SPECIES_ESPEON 0xC4
#define SPECIES_UMBREON 0xC5
#define SPECIES_MURKROW 0xC6
#define SPECIES_SLOWKING 0xC7
#define SPECIES_MISDREAVUS 0xC8
#define SPECIES_UNOWN 0xC9
#define SPECIES_WOBBUFFET 0xCA
#define SPECIES_GIRAFARIG 0xCB
#define SPECIES_PINECO 0xCC
#define SPECIES_FORRETRESS 0xCD
#define SPECIES_DUNSPARCE 0xCE
#define SPECIES_GLIGAR 0xCF
#define SPECIES_STEELIX 0xD0
#define SPECIES_SNUBBULL 0xD1
#define SPECIES_GRANBULL 0xD2
#define SPECIES_QWILFISH 0xD3
#define SPECIES_SCIZOR 0xD4
#define SPECIES_SHUCKLE 0xD5
#define SPECIES_HERACROSS 0xD6
#define SPECIES_SNEASEL 0xD7
#define SPECIES_TEDDIURSA 0xD8
#define SPECIES_URSARING 0xD9
#define SPECIES_SLUGMA 0xDA
#define SPECIES_MAGCARGO 0xDB
#define SPECIES_SWINUB 0xDC
#define SPECIES_PILOSWINE 0xDD
#define SPECIES_CORSOLA 0xDE
#define SPECIES_REMORAID 0xDF
#define SPECIES_OCTILLERY 0xE0
#define SPECIES_DELIBIRD 0xE1
#define SPECIES_MANTINE 0xE2
#define SPECIES_SKARMORY 0xE3
#define SPECIES_HOUNDOUR 0xE4
#define SPECIES_HOUNDOOM 0xE5
#define SPECIES_KINGDRA 0xE6
#define SPECIES_PHANPY 0xE7
#define SPECIES_DONPHAN 0xE8
#define SPECIES_PORYGON2 0xE9
#define SPECIES_STANTLER 0xEA
#define SPECIES_SMEARGLE 0xEB
#define SPECIES_TYROGUE 0xEC
#define SPECIES_HITMONTOP 0xED
#define SPECIES_SMOOCHUM 0xEE
#define SPECIES_ELEKID 0xEF
#define SPECIES_MAGBY 0xF0
#define SPECIES_MILTANK 0xF1
#define SPECIES_BLISSEY 0xF2
#define SPECIES_RAIKOU 0xF3
#define SPECIES_ENTEI 0xF4
#define SPECIES_SUICUNE 0xF5
#define SPECIES_LARVITAR 0xF6
#define SPECIES_PUPITAR 0xF7
#define SPECIES_TYRANITAR 0xF8
#define SPECIES_LUGIA 0xF9
#define SPECIES_HO_OH 0xFA
#define SPECIES_CELEBI 0xFB

#define SPECIES_TREECKO 0x115
#define SPECIES_GROVYLE 0x116
#define SPECIES_SCEPTILE 0x117
#define SPECIES_TORCHIC 0x118
#define SPECIES_COMBUSKEN 0x119
#define SPECIES_BLAZIKEN 0x11A
#define SPECIES_MUDKIP 0x11B
#define SPECIES_MARSHTOMP 0x11C
#define SPECIES_SWAMPERT 0x11D
#define SPECIES_POOCHYENA 0x11E
#define SPECIES_MIGHTYENA 0x11F
#define SPECIES_ZIGZAGOON 0x120
#define SPECIES_LINOONE 0x121
#define SPECIES_WURMPLE 0x122
#define SPECIES_SILCOON 0x123
#define SPECIES_BEAUTIFLY 0x124
#define SPECIES_CASCOON 0x125
#define SPECIES_DUSTOX 0x126
#define SPECIES_LOTAD 0x127
#define SPECIES_LOMBRE 0x128
#define SPECIES_LUDICOLO 0x129
#define SPECIES_SEEDOT 0x12A
#define SPECIES_NUZLEAF 0x12B
#define SPECIES_SHIFTRY 0x12C
#define SPECIES_NINCADA 0x12D
#define SPECIES_NINJASK 0x12E
#define SPECIES_SHEDINJA 0x12F
#define SPECIES_TAILLOW 0x130
#define SPECIES_SWELLOW 0x131
#define SPECIES_SHROOMISH 0x132
#define SPECIES_BRELOOM 0x133
#define SPECIES_SPINDA 0x134
#define SPECIES_WINGULL 0x135
#define SPECIES_PELIPPER 0x136
#define SPECIES_SURSKIT 0x137
#define SPECIES_MASQUERAIN 0x138
#define SPECIES_WAILMER 0x139
#define SPECIES_WAILORD 0x13A
#define SPECIES_SKITTY 0x13B
#define SPECIES_DELCATTY 0x13C
#define SPECIES_KECLEON 0x13D
#define SPECIES_BALTOY 0x13E
#define SPECIES_CLAYDOL 0x13F
#define SPECIES_NOSEPASS 0x140
#define SPECIES_TORKOAL 0x141
#define SPECIES_SABLEYE 0x142
#define SPECIES_BARBOACH 0x143
#define SPECIES_WHISCASH 0x144
#define SPECIES_LUVDISC 0x145
#define SPECIES_CORPHISH 0x146
#define SPECIES_CRAWDAUNT 0x147
#define SPECIES_FEEBAS 0x148
#define SPECIES_MILOTIC 0x149
#define SPECIES_CARVANHA 0x14A
#define SPECIES_SHARPEDO 0x14B
#define SPECIES_TRAPINCH 0x14C
#define SPECIES_VIBRAVA 0x14D
#define SPECIES_FLYGON 0x14E
#define SPECIES_MAKUHITA 0x14F
#define SPECIES_HARIYAMA 0x150
#define SPECIES_ELECTRIKE 0x151
#define SPECIES_MANECTRIC 0x152
#define SPECIES_NUMEL 0x153
#define SPECIES_CAMERUPT 0x154
#define SPECIES_SPHEAL 0x155
#define SPECIES_SEALEO 0x156
#define SPECIES_WALREIN 0x157
#define SPECIES_CACNEA 0x158
#define SPECIES_CACTURNE 0x159
#define SPECIES_SNORUNT 0x15A
#define SPECIES_GLALIE 0x15B
#define SPECIES_LUNATONE 0x15C
#define SPECIES_SOLROCK 0x15D
#define SPECIES_AZURILL 0x15E
#define SPECIES_SPOINK 0x15F
#define SPECIES_GRUMPIG 0x160
#define SPECIES_PLUSLE 0x161
#define SPECIES_MINUN 0x162
#define SPECIES_MAWILE 0x163
#define SPECIES_MEDITITE 0x164
#define SPECIES_MEDICHAM 0x165
#define SPECIES_SWABLU 0x166
#define SPECIES_ALTARIA 0x167
#define SPECIES_WYNAUT 0x168
#define SPECIES_DUSKULL 0x169
#define SPECIES_DUSCLOPS 0x16A
#define SPECIES_ROSELIA 0x16B
#define SPECIES_SLAKOTH 0x16C
#define SPECIES_VIGOROTH 0x16D
#define SPECIES_SLAKING 0x16E
#define SPECIES_GULPIN 0x16F
#define SPECIES_SWALOT 0x170
#define SPECIES_TROPIUS 0x171
#define SPECIES_WHISMUR 0x172
#define SPECIES_LOUDRED 0x173
#define SPECIES_EXPLOUD 0x174
#define SPECIES_CLAMPERL 0x175
#define SPECIES_HUNTAIL 0x176
#define SPECIES_GOREBYSS 0x177
#define SPECIES_ABSOL 0x178
#define SPECIES_SHUPPET 0x179
#define SPECIES_BANETTE 0x17A
#define SPECIES_SEVIPER 0x17B
#define SPECIES_ZANGOOSE 0x17C
#define SPECIES_RELICANTH 0x17D
#define SPECIES_ARON 0x17E
#define SPECIES_LAIRON 0x17F
#define SPECIES_AGGRON 0x180
#define SPECIES_CASTFORM 0x181
#define SPECIES_VOLBEAT 0x182
#define SPECIES_ILLUMISE 0x183
#define SPECIES_LILEEP 0x184
#define SPECIES_CRADILY 0x185
#define SPECIES_ANORITH 0x186
#define SPECIES_ARMALDO 0x187
#define SPECIES_RALTS 0x188
#define SPECIES_KIRLIA 0x189
#define SPECIES_GARDEVOIR 0x18A
#define SPECIES_BAGON 0x18B
#define SPECIES_SHELGON 0x18C
#define SPECIES_SALAMENCE 0x18D
#define SPECIES_BELDUM 0x18E
#define SPECIES_METANG 0x18F
#define SPECIES_METAGROSS 0x190
#define SPECIES_REGIROCK 0x191
#define SPECIES_REGICE 0x192
#define SPECIES_REGISTEEL 0x193
#define SPECIES_KYOGRE 0x194
#define SPECIES_GROUDON 0x195
#define SPECIES_RAYQUAZA 0x196
#define SPECIES_LATIAS 0x197
#define SPECIES_LATIOS 0x198
#define SPECIES_JIRACHI 0x199
#define SPECIES_DEOXYS 0x19A
#define SPECIES_CHIMECHO 0x19B

#define SPECIES_EGG 0x19C
#define SPECIES_UNOWN_B 0x19D
#define SPECIES_UNOWN_C 0x19E
#define SPECIES_UNOWN_D 0x19F
#define SPECIES_UNOWN_E 0x1A0
#define SPECIES_UNOWN_F 0x1A1
#define SPECIES_UNOWN_G 0x1A2
#define SPECIES_UNOWN_H 0x1A3
#define SPECIES_UNOWN_I 0x1A4
#define SPECIES_UNOWN_J 0x1A5
#define SPECIES_UNOWN_K 0x1A6
#define SPECIES_UNOWN_L 0x1A7
#define SPECIES_UNOWN_M 0x1A8
#define SPECIES_UNOWN_N 0x1A9
#define SPECIES_UNOWN_O 0x1AA
#define SPECIES_UNOWN_P 0x1AB
#define SPECIES_UNOWN_Q 0x1AC
#define SPECIES_UNOWN_R 0x1AD
#define SPECIES_UNOWN_S 0x1AE
#define SPECIES_UNOWN_T 0x1AF
#define SPECIES_UNOWN_U 0x1B0
#define SPECIES_UNOWN_V 0x1B1
#define SPECIES_UNOWN_W 0x1B2
#define SPECIES_UNOWN_X 0x1B3
#define SPECIES_UNOWN_Y 0x1B4
#define SPECIES_UNOWN_Z 0x1B5
#define SPECIES_UNOWN_EXCLAMATION 0x1B6
#define SPECIES_UNOWN_QUESTION 0x1B7

#define NUM_SPECIES (SPECIES_UNOWN_QUESTION + 1)
