#include "defines.h"
#include "../include/pokedex.h"
#include "../include/text.h"

const struct PokedexEntry gPokedexEntries[NATIONAL_DEX_COUNT] =
{
	[NATIONAL_DEX_NONE] =
	{
		.categoryName = {_U, _n, _k, _n, _o, _w, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 0,
		.weight = 0,
		.description = (const u8*) 0x8444c35,
		.unusedDescription = (const u8*) 0x8444cb1,
		.pokemonScale = 256,
		.pokemonOffset = 0,
		.trainerScale = 256,
		.trainerOffset = 0,
	},
	[NATIONAL_DEX_BULBORBLARVA] =
	{
		.categoryName = {_S, _e, _e, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 7,
		.weight = 69,
		.description = (const u8*) 0x8444cb2,
		.unusedDescription = (const u8*) 0x8444d11,
		.pokemonScale = 356,
		.pokemonOffset = 16,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BULBORB] =
	{
		.categoryName = {_S, _e, _e, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 130,
		.description = (const u8*) 0x8444d1c,
		.unusedDescription = (const u8*) 0x8444d76,
		.pokemonScale = 332,
		.pokemonOffset = 11,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_JUMBOBULBORB] =
	{
		.categoryName = {_S, _e, _e, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 20,
		.weight = 1000,
		.description = (const u8*) 0x8444d8c,
		.unusedDescription = (const u8*) 0x8444dde,
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 375,
		.trainerOffset = 6,
	},
	[NATIONAL_DEX_FIERYBLOWLET] =
	{
		.categoryName = {_L, _i, _z, _a, _r, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 85,
		.description = (const u8*) 0x8444de8,
		.unusedDescription = (const u8*) 0x8444e47,
		.pokemonScale = 410,
		.pokemonOffset = 16,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_FIERYBLOWHOG] =
	{
		.categoryName = {_F, _l, _a, _m, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 190,
		.description = (const u8*) 0x8444e59,
		.unusedDescription = (const u8*) 0x8444eac,
		.pokemonScale = 294,
		.pokemonOffset = 8,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_TITANBLOWHOG] =
	{
		.categoryName = {_F, _l, _a, _m, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 17,
		.weight = 905,
		.description = (const u8*) 0x8444ec6,
		.unusedDescription = (const u8*) 0x8444f17,
		.pokemonScale = 271,
		.pokemonOffset = 0,
		.trainerScale = 317,
		.trainerOffset = 3,
	},
	[NATIONAL_DEX_WOLPOLE] =
	{
		.categoryName = {_T, _i, _n, _y, _SPACE, _T, _u, _r, _t, _l, _e, _END},
		.height = 5,
		.weight = 90,
		.description = (const u8*) 0x8444f39,
		.unusedDescription = (const u8*) 0x8444f7f,
		.pokemonScale = 412,
		.pokemonOffset = 16,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_YELLOWWOLLYHOP] =
	{
		.categoryName = {_T, _u, _r, _t, _l, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 225,
		.description = (const u8*) 0x8444f93,
		.unusedDescription = (const u8*) 0x8444fe6,
		.pokemonScale = 334,
		.pokemonOffset = 9,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MASTERHOP] =
	{
		.categoryName = {_S, _h, _e, _l, _l, _f, _i, _s, _h, _END, _SPACE, _SPACE},
		.height = 16,
		.weight = 855,
		.description = (const u8*) 0x8444fee,
		.unusedDescription = (const u8*) 0x8445049,
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 329,
		.trainerOffset = 3,
	},
	[NATIONAL_DEX_FLINTBEETLE] =
	{
		.categoryName = {_W, _o, _r, _m, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 3,
		.weight = 29,
		.description = (const u8*) 0x8445059,
		.unusedDescription = (const u8*) 0x84450ae,
		.pokemonScale = 549,
		.pokemonOffset = 20,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DOODLEBUG] =
	{
		.categoryName = {_C, _o, _c, _o, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 7,
		.weight = 99,
		.description = (const u8*) 0x84450cc,
		.unusedDescription = (const u8*) 0x844510e,
		.pokemonScale = 350,
		.pokemonOffset = 18,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_GLINTBEETLE] =
	{
		.categoryName = {_B, _u, _t, _t, _e, _r, _f, _l, _y, _END, _SPACE, _SPACE},
		.height = 11,
		.weight = 320,
		.description = (const u8*) 0x8445138,
		.unusedDescription = (const u8*) 0x844516f,
		.pokemonScale = 312,
		.pokemonOffset = 2,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SWOOPINGSNITCHBUG] =
	{
		.categoryName = {_H, _a, _i, _r, _y, _SPACE, _B, _u, _g, _END, _SPACE, _SPACE},
		.height = 3,
		.weight = 32,
		.description = (const u8*) 0x844519f,
		.unusedDescription = (const u8*) 0x84451d2,
		.pokemonScale = 455,
		.pokemonOffset = 19,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BUMBLINGSNITCHBUG] =
	{
		.categoryName = {_C, _o, _c, _o, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 100,
		.description = (const u8*) 0x844520b,
		.unusedDescription = (const u8*) 0x8445233,
		.pokemonScale = 424,
		.pokemonOffset = 14,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DIRIGIBUG] =
	{
		.categoryName = {_P, _o, _i, _s, _o, _n, _SPACE, _B, _e, _e, _END, _SPACE},
		.height = 10,
		.weight = 295,
		.description = (const u8*) 0x844527b,
		.unusedDescription = (const u8*) 0x8445295,
		.pokemonScale = 366,
		.pokemonOffset = 2,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SNOWBULBORB] =
	{
		.categoryName = {_T, _i, _n, _y, _SPACE, _B, _i, _r, _d, _END, _SPACE, _SPACE},
		.height = 3,
		.weight = 18,
		.description = (const u8*) 0x84452e7,
		.unusedDescription = (const u8*) 0x84452fc,
		.pokemonScale = 492,
		.pokemonOffset = 18,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DWARFFROSTYBULBORB] =
	{
		.categoryName = {_B, _i, _r, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 300,
		.description = (const u8*) 0x8445348,
		.unusedDescription = (const u8*) 0x844535d,
		.pokemonScale = 334,
		.pokemonOffset = 11,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_FROSTYBULBORB] =
	{
		.categoryName = {_B, _i, _r, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 15,
		.weight = 395,
		.description = (const u8*) 0x84453ba,
		.unusedDescription = (const u8*) 0x84453c7,
		.pokemonScale = 269,
		.pokemonOffset = 65534,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CRUMBUG] =
	{
		.categoryName = {_R, _a, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 3,
		.weight = 35,
		.description = (const u8*) 0x8445423,
		.unusedDescription = (const u8*) 0x8445426,
		.pokemonScale = 481,
		.pokemonOffset = 18,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BREADBUG] =
	{
		.categoryName = {_R, _a, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 7,
		.weight = 185,
		.description = (const u8*) 0x8445490,
		.unusedDescription = (const u8*) 0x844547f,
		.pokemonScale = 401,
		.pokemonOffset = 14,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_GIANTBREADBUG] =
	{
		.categoryName = {_T, _i, _n, _y, _SPACE, _B, _i, _r, _d, _END, _SPACE, _SPACE},
		.height = 3,
		.weight = 20,
		.description = (const u8*) 0x84454e9,
		.unusedDescription = (const u8*) 0x84454e9,
		.pokemonScale = 571,
		.pokemonOffset = 19,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_EMPERORBULBLAX] =
	{
		.categoryName = {_B, _e, _a, _k, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 380,
		.description = (const u8*) 0x8445553,
		.unusedDescription = (const u8*) 0x8445550,
		.pokemonScale = 282,
		.pokemonOffset = 65535,
		.trainerScale = 272,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SOVREIGNBULBLAX] =
	{
		.categoryName = {_S, _n, _a, _k, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 20,
		.weight = 69,
		.description = (const u8*) 0x84455c3,
		.unusedDescription = (const u8*) 0x84455b5,
		.pokemonScale = 298,
		.pokemonOffset = 13,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DWARFBULBEAR] =
	{
		.categoryName = {_C, _o, _b, _r, _a, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 35,
		.weight = 650,
		.description = (const u8*) 0x8445630,
		.unusedDescription = (const u8*) 0x844561c,
		.pokemonScale = 256,
		.pokemonOffset = 0,
		.trainerScale = 296,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_SPOTTYBULBEAR] =
	{
		.categoryName = {_M, _o, _u, _s, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 4,
		.weight = 60,
		.description = (const u8*) 0x84456a2,
		.unusedDescription = (const u8*) 0x8445685,
		.pokemonScale = 479,
		.pokemonOffset = 16,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_HONEYWISP] =
	{
		.categoryName = {_M, _o, _u, _s, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 8,
		.weight = 300,
		.description = (const u8*) 0x844570b,
		.unusedDescription = (const u8*) 0x84456ea,
		.pokemonScale = 426,
		.pokemonOffset = 10,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DANDELFLY] =
	{
		.categoryName = {_M, _o, _u, _s, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 120,
		.description = (const u8*) 0x844577c,
		.unusedDescription = (const u8*) 0x844574b,
		.pokemonScale = 370,
		.pokemonOffset = 15,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DOWNYSNAGRET] =
	{
		.categoryName = {_M, _o, _u, _s, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 295,
		.description = (const u8*) 0x84457dd,
		.unusedDescription = (const u8*) 0x84457b4,
		.pokemonScale = 341,
		.pokemonOffset = 10,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BURROWINGSNAGRET] =
	{
		.categoryName = {_P, _o, _i, _s, _o, _n, _SPACE, _P, _i, _n, _END, _SPACE},
		.height = 4,
		.weight = 70,
		.description = (const u8*) 0x8445846,
		.unusedDescription = (const u8*) 0x844581a,
		.pokemonScale = 488,
		.pokemonOffset = 19,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PILEATEDSNAGRET] =
	{
		.categoryName = {_P, _o, _i, _s, _o, _n, _SPACE, _P, _i, _n, _END, _SPACE},
		.height = 8,
		.weight = 200,
		.description = (const u8*) 0x84458ba,
		.unusedDescription = (const u8*) 0x8445874,
		.pokemonScale = 381,
		.pokemonOffset = 13,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_FEMALESHEARGRUB] =
	{
		.categoryName = {_D, _r, _i, _l, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 600,
		.description = (const u8*) 0x8445920,
		.unusedDescription = (const u8*) 0x84458da,
		.pokemonScale = 283,
		.pokemonOffset = 2,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SWARMINGSHEARGRUB] =
	{
		.categoryName = {_P, _o, _i, _s, _o, _n, _SPACE, _P, _i, _n, _END, _SPACE},
		.height = 5,
		.weight = 90,
		.description = (const u8*) 0x8445989,
		.unusedDescription = (const u8*) 0x8445949,
		.pokemonScale = 480,
		.pokemonOffset = 17,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MAMASHEARGRUB] =
	{
		.categoryName = {_P, _o, _i, _s, _o, _n, _SPACE, _P, _i, _n, _END, _SPACE},
		.height = 9,
		.weight = 195,
		.description = (const u8*) 0x84459fd,
		.unusedDescription = (const u8*) 0x84459af,
		.pokemonScale = 408,
		.pokemonOffset = 13,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MALESHEARGRUB] =
	{
		.categoryName = {_D, _r, _i, _l, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 14,
		.weight = 620,
		.description = (const u8*) 0x8445a64,
		.unusedDescription = (const u8*) 0x8445a17,
		.pokemonScale = 304,
		.pokemonOffset = 3,
		.trainerScale = 323,
		.trainerOffset = 2,
	},
	[NATIONAL_DEX_SHEARWIG] =
	{
		.categoryName = {_F, _a, _i, _r, _y, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 75,
		.description = (const u8*) 0x8445ad2,
		.unusedDescription = (const u8*) 0x8445a7a,
		.pokemonScale = 425,
		.pokemonOffset = 18,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_QUEENSHEARWIG] =
	{
		.categoryName = {_F, _a, _i, _r, _y, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 400,
		.description = (const u8*) 0x8445b31,
		.unusedDescription = (const u8*) 0x8445ada,
		.pokemonScale = 256,
		.pokemonOffset = 3,
		.trainerScale = 272,
		.trainerOffset = 65535,
	},
	[NATIONAL_DEX_ARISTOCRABOFFSPRING] =
	{
		.categoryName = {_F, _o, _x, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 99,
		.description = (const u8*) 0x8445b94,
		.unusedDescription = (const u8*) 0x8445b32,
		.pokemonScale = 497,
		.pokemonOffset = 18,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ARISTOCRAB] =
	{
		.categoryName = {_F, _o, _x, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 199,
		.description = (const u8*) 0x8445bec,
		.unusedDescription = (const u8*) 0x8445b93,
		.pokemonScale = 339,
		.pokemonOffset = 6,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_GOOLIX] =
	{
		.categoryName = {_B, _a, _l, _l, _o, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 5,
		.weight = 55,
		.description = (const u8*) 0x8445c44,
		.unusedDescription = (const u8*) 0x8445bf9,
		.pokemonScale = 419,
		.pokemonOffset = 19,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_FOOLIX] =
	{
		.categoryName = {_B, _a, _l, _l, _o, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 120,
		.description = (const u8*) 0x8445caa,
		.unusedDescription = (const u8*) 0x8445c61,
		.pokemonScale = 328,
		.pokemonOffset = 9,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ARCTICCANNONLARVA] =
	{
		.categoryName = {_B, _a, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 8,
		.weight = 75,
		.description = (const u8*) 0x8445d12,
		.unusedDescription = (const u8*) 0x8445cca,
		.pokemonScale = 355,
		.pokemonOffset = 65532,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ARCTICCANNONBEETLE] =
	{
		.categoryName = {_B, _a, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 16,
		.weight = 550,
		.description = (const u8*) 0x8445d7b,
		.unusedDescription = (const u8*) 0x8445d34,
		.pokemonScale = 291,
		.pokemonOffset = 0,
		.trainerScale = 296,
		.trainerOffset = 2,
	},
	[NATIONAL_DEX_SKITTERLEAF] =
	{
		.categoryName = {_W, _e, _e, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 5,
		.weight = 54,
		.description = (const u8*) 0x8445de0,
		.unusedDescription = (const u8*) 0x8445da0,
		.pokemonScale = 423,
		.pokemonOffset = 15,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DESICCATEDSKITTERLEAF] =
	{
		.categoryName = {_W, _e, _e, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 8,
		.weight = 86,
		.description = (const u8*) 0x8445e4c,
		.unusedDescription = (const u8*) 0x8445e07,
		.pokemonScale = 329,
		.pokemonOffset = 10,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ARMOREDCANNONLARVA] =
	{
		.categoryName = {_F, _l, _o, _w, _e, _r, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 186,
		.description = (const u8*) 0x8445eba,
		.unusedDescription = (const u8*) 0x8445e6f,
		.pokemonScale = 256,
		.pokemonOffset = 4,
		.trainerScale = 272,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ARMOREDCANNONBEETLE] =
	{
		.categoryName = {_M, _u, _s, _h, _r, _o, _o, _m, _END, _SPACE, _SPACE, _SPACE},
		.height = 3,
		.weight = 54,
		.description = (const u8*) 0x8445f23,
		.unusedDescription = (const u8*) 0x8445ed6,
		.pokemonScale = 546,
		.pokemonOffset = 21,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_HORNEDCANNONBEETLE] =
	{
		.categoryName = {_M, _u, _s, _h, _r, _o, _o, _m, _END, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 295,
		.description = (const u8*) 0x8445f88,
		.unusedDescription = (const u8*) 0x8445f42,
		.pokemonScale = 307,
		.pokemonOffset = 8,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CREEPINGCHRYSANTHEMUM] =
	{
		.categoryName = {_I, _n, _s, _e, _c, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 300,
		.description = (const u8*) 0x8445feb,
		.unusedDescription = (const u8*) 0x8445fa0,
		.pokemonScale = 360,
		.pokemonOffset = 14,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_STARTLESPORE] =
	{
		.categoryName = {_P, _o, _i, _s, _o, _n, _SPACE, _M, _o, _t, _h, _END},
		.height = 15,
		.weight = 125,
		.description = (const u8*) 0x8446051,
		.unusedDescription = (const u8*) 0x8446009,
		.pokemonScale = 256,
		.pokemonOffset = 3,
		.trainerScale = 293,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_HERMITCRAWMAD] =
	{
		.categoryName = {_M, _o, _l, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 2,
		.weight = 8,
		.description = (const u8*) 0x84460ba,
		.unusedDescription = (const u8*) 0x8446078,
		.pokemonScale = 706,
		.pokemonOffset = 22,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BUGEYEDCRAWMAD] =
	{
		.categoryName = {_M, _o, _l, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 7,
		.weight = 333,
		.description = (const u8*) 0x8446129,
		.unusedDescription = (const u8*) 0x84460e2,
		.pokemonScale = 384,
		.pokemonOffset = 14,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DWARFBULBORB] =
	{
		.categoryName = {_S, _c, _r, _a, _t, _c, _h, _SPACE, _C, _a, _t, _END},
		.height = 4,
		.weight = 42,
		.description = (const u8*) 0x844618f,
		.unusedDescription = (const u8*) 0x8446143,
		.pokemonScale = 480,
		.pokemonOffset = 17,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DWARFORANGEBULBORB] =
	{
		.categoryName = {_C, _l, _a, _s, _s, _y, _SPACE, _C, _a, _t, _END, _SPACE},
		.height = 10,
		.weight = 320,
		.description = (const u8*) 0x84461f1,
		.unusedDescription = (const u8*) 0x84461a6,
		.pokemonScale = 320,
		.pokemonOffset = 10,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BEADYLONGLEGS] =
	{
		.categoryName = {_D, _u, _c, _k, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 8,
		.weight = 196,
		.description = (const u8*) 0x844626b,
		.unusedDescription = (const u8*) 0x8446213,
		.pokemonScale = 347,
		.pokemonOffset = 11,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_RAGINGLONGLEGS] =
	{
		.categoryName = {_D, _u, _c, _k, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 17,
		.weight = 766,
		.description = (const u8*) 0x84462d8,
		.unusedDescription = (const u8*) 0x8446273,
		.pokemonScale = 272,
		.pokemonOffset = 4,
		.trainerScale = 287,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_BALDYLONGLEGS] =
	{
		.categoryName = {_P, _i, _g, _SPACE, _M, _o, _n, _k, _e, _y, _END, _SPACE},
		.height = 5,
		.weight = 280,
		.description = (const u8*) 0x8446348,
		.unusedDescription = (const u8*) 0x84462e5,
		.pokemonScale = 388,
		.pokemonOffset = 16,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SHAGGYLONGLEGS] =
	{
		.categoryName = {_P, _i, _g, _SPACE, _M, _o, _n, _k, _e, _y, _END, _SPACE},
		.height = 10,
		.weight = 320,
		.description = (const u8*) 0x84463ba,
		.unusedDescription = (const u8*) 0x844634b,
		.pokemonScale = 326,
		.pokemonOffset = 8,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BULBMIN] =
	{
		.categoryName = {_P, _u, _p, _p, _y, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 7,
		.weight = 190,
		.description = (const u8*) 0x8446429,
		.unusedDescription = (const u8*) 0x84463b1,
		.pokemonScale = 346,
		.pokemonOffset = 14,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ADULTBULBMIN] =
	{
		.categoryName = {_L, _e, _g, _e, _n, _d, _a, _r, _y, _END, _SPACE, _SPACE},
		.height = 19,
		.weight = 1550,
		.description = (const u8*) 0x8446484,
		.unusedDescription = (const u8*) 0x8446416,
		.pokemonScale = 256,
		.pokemonOffset = 65535,
		.trainerScale = 312,
		.trainerOffset = 2,
	},
	[NATIONAL_DEX_SCORNET] =
	{
		.categoryName = {_T, _a, _d, _p, _o, _l, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 124,
		.description = (const u8*) 0x84464e2,
		.unusedDescription = (const u8*) 0x844647d,
		.pokemonScale = 353,
		.pokemonOffset = 17,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SCORNETMAESTRO] =
	{
		.categoryName = {_T, _a, _d, _p, _o, _l, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 200,
		.description = (const u8*) 0x844655a,
		.unusedDescription = (const u8*) 0x84464db,
		.pokemonScale = 288,
		.pokemonOffset = 10,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BURROWNIT] =
	{
		.categoryName = {_T, _a, _d, _p, _o, _l, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 540,
		.description = (const u8*) 0x84465bf,
		.unusedDescription = (const u8*) 0x844653f,
		.pokemonScale = 256,
		.pokemonOffset = 5,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_JOUSTMITE] =
	{
		.categoryName = {_P, _s, _i, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 9,
		.weight = 195,
		.description = (const u8*) 0x844662c,
		.unusedDescription = (const u8*) 0x844659a,
		.pokemonScale = 374,
		.pokemonOffset = 14,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_FLIGHTYJOUSTMITE] =
	{
		.categoryName = {_P, _s, _i, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 565,
		.description = (const u8*) 0x8446687,
		.unusedDescription = (const u8*) 0x84465f6,
		.pokemonScale = 272,
		.pokemonOffset = 2,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_VOLATILEDWEEVIL] =
	{
		.categoryName = {_P, _s, _i, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 15,
		.weight = 480,
		.description = (const u8*) 0x84466e8,
		.unusedDescription = (const u8*) 0x8446663,
		.pokemonScale = 272,
		.pokemonOffset = 65535,
		.trainerScale = 271,
		.trainerOffset = 65535,
	},
	[NATIONAL_DEX_MANATLEGS] =
	{
		.categoryName = {_S, _u, _p, _e, _r, _p, _o, _w, _e, _r, _END, _SPACE},
		.height = 8,
		.weight = 195,
		.description = (const u8*) 0x8446755,
		.unusedDescription = (const u8*) 0x84466c9,
		.pokemonScale = 320,
		.pokemonOffset = 12,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SKUTTERCHUCK] =
	{
		.categoryName = {_S, _u, _p, _e, _r, _p, _o, _w, _e, _r, _END, _SPACE},
		.height = 15,
		.weight = 705,
		.description = (const u8*) 0x84467c4,
		.unusedDescription = (const u8*) 0x8446731,
		.pokemonScale = 304,
		.pokemonOffset = 6,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CALCIFIEDCRUSHBLAT] =
	{
		.categoryName = {_S, _u, _p, _e, _r, _p, _o, _w, _e, _r, _END, _SPACE},
		.height = 16,
		.weight = 1300,
		.description = (const u8*) 0x844682c,
		.unusedDescription = (const u8*) 0x844679a,
		.pokemonScale = 278,
		.pokemonOffset = 2,
		.trainerScale = 283,
		.trainerOffset = 0,
	},
	[NATIONAL_DEX_ARACHNODE] =
	{
		.categoryName = {_F, _l, _o, _w, _e, _r, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 7,
		.weight = 40,
		.description = (const u8*) 0x8446888,
		.unusedDescription = (const u8*) 0x8446802,
		.pokemonScale = 354,
		.pokemonOffset = 16,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MOLDYDWARFBULBORB] =
	{
		.categoryName = {_F, _l, _y, _c, _a, _t, _c, _h, _e, _r, _END, _SPACE},
		.height = 10,
		.weight = 64,
		.description = (const u8*) 0x84468f6,
		.unusedDescription = (const u8*) 0x8446861,
		.pokemonScale = 256,
		.pokemonOffset = 65535,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MOLDYSLOOCH] =
	{
		.categoryName = {_F, _l, _y, _c, _a, _t, _c, _h, _e, _r, _END, _SPACE},
		.height = 17,
		.weight = 155,
		.description = (const u8*) 0x8446955,
		.unusedDescription = (const u8*) 0x84468c7,
		.pokemonScale = 256,
		.pokemonOffset = 2,
		.trainerScale = 302,
		.trainerOffset = 2,
	},
	[NATIONAL_DEX_TOXSTOOL] =
	{
		.categoryName = {_J, _e, _l, _l, _y, _f, _i, _s, _h, _END, _SPACE, _SPACE},
		.height = 9,
		.weight = 455,
		.description = (const u8*) 0x84469bd,
		.unusedDescription = (const u8*) 0x8446937,
		.pokemonScale = 256,
		.pokemonOffset = 0,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PHOSBAT] =
	{
		.categoryName = {_J, _e, _l, _l, _y, _f, _i, _s, _h, _END, _SPACE, _SPACE},
		.height = 16,
		.weight = 550,
		.description = (const u8*) 0x8446a17,
		.unusedDescription = (const u8*) 0x84469a0,
		.pokemonScale = 272,
		.pokemonOffset = 65535,
		.trainerScale = 312,
		.trainerOffset = 0,
	},
	[NATIONAL_DEX_VEHEAMOTHPHOSBAT] =
	{
		.categoryName = {_R, _o, _c, _k, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 4,
		.weight = 200,
		.description = (const u8*) 0x8446a80,
		.unusedDescription = (const u8*) 0x8446a05,
		.pokemonScale = 330,
		.pokemonOffset = 17,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PUCKERINGBLINNOW] =
	{
		.categoryName = {_R, _o, _c, _k, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 1050,
		.description = (const u8*) 0x8446af0,
		.unusedDescription = (const u8*) 0x8446a6b,
		.pokemonScale = 272,
		.pokemonOffset = 8,
		.trainerScale = 305,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_SPUTTLEFISH] =
	{
		.categoryName = {_M, _e, _g, _a, _t, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 14,
		.weight = 3000,
		.description = (const u8*) 0x8446b56,
		.unusedDescription = (const u8*) 0x8446ad9,
		.pokemonScale = 266,
		.pokemonOffset = 3,
		.trainerScale = 298,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_PRICKLEPUFF] =
	{
		.categoryName = {_F, _i, _r, _e, _SPACE, _H, _o, _r, _s, _e, _END, _SPACE},
		.height = 10,
		.weight = 300,
		.description = (const u8*) 0x8446bc4,
		.unusedDescription = (const u8*) 0x8446b41,
		.pokemonScale = 288,
		.pokemonOffset = 7,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_UJADANI] =
	{
		.categoryName = {_F, _i, _r, _e, _SPACE, _H, _o, _r, _s, _e, _END, _SPACE},
		.height = 17,
		.weight = 950,
		.description = (const u8*) 0x8446c23,
		.unusedDescription = (const u8*) 0x8446b9f,
		.pokemonScale = 282,
		.pokemonOffset = 65535,
		.trainerScale = 312,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_MITITE] =
	{
		.categoryName = {_D, _o, _p, _e, _y, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 360,
		.description = (const u8*) 0x8446c8c,
		.unusedDescription = (const u8*) 0x8446c01,
		.pokemonScale = 271,
		.pokemonOffset = 10,
		.trainerScale = 272,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_WITHERINGBLOWHOG] =
	{
		.categoryName = {_H, _e, _r, _m, _i, _t, _SPACE, _C, _r, _a, _b, _END},
		.height = 16,
		.weight = 785,
		.description = (const u8*) 0x8446d05,
		.unusedDescription = (const u8*) 0x8446c61,
		.pokemonScale = 257,
		.pokemonOffset = 65534,
		.trainerScale = 312,
		.trainerOffset = 0,
	},
	[NATIONAL_DEX_PUFFYBLOWHOG] =
	{
		.categoryName = {_M, _a, _g, _n, _e, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 3,
		.weight = 60,
		.description = (const u8*) 0x8446d74,
		.unusedDescription = (const u8*) 0x8446cc8,
		.pokemonScale = 294,
		.pokemonOffset = 65528,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MINIATURESNOOTWHACKER] =
	{
		.categoryName = {_M, _a, _g, _n, _e, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 600,
		.description = (const u8*) 0x8446ddb,
		.unusedDescription = (const u8*) 0x8446d2e,
		.pokemonScale = 293,
		.pokemonOffset = 65532,
		.trainerScale = 273,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MAMMOTHSNOOTWHACKER] =
	{
		.categoryName = {_W, _i, _l, _d, _SPACE, _D, _u, _c, _k, _END, _SPACE, _SPACE},
		.height = 8,
		.weight = 150,
		.description = (const u8*) 0x8446e41,
		.unusedDescription = (const u8*) 0x8446d96,
		.pokemonScale = 317,
		.pokemonOffset = 65534,
		.trainerScale = 256,
		.trainerOffset = 65533,
	},
	[NATIONAL_DEX_PYROCLASTICSLOOCH] =
	{
		.categoryName = {_T, _w, _i, _n, _SPACE, _B, _i, _r, _d, _END, _SPACE, _SPACE},
		.height = 14,
		.weight = 392,
		.description = (const u8*) 0x8446ea9,
		.unusedDescription = (const u8*) 0x8446dfe,
		.pokemonScale = 256,
		.pokemonOffset = 3,
		.trainerScale = 287,
		.trainerOffset = 0,
	},
	[NATIONAL_DEX_LESSERSPOTTEDJELLYFLOAT] =
	{
		.categoryName = {_T, _r, _i, _p, _l, _e, _SPACE, _B, _i, _r, _d, _END},
		.height = 18,
		.weight = 852,
		.description = (const u8*) 0x8446f16,
		.unusedDescription = (const u8*) 0x8446e62,
		.pokemonScale = 272,
		.pokemonOffset = 65534,
		.trainerScale = 296,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_GREATERSPOTTEDJELLYFLOAT] =
	{
		.categoryName = {_S, _e, _a, _SPACE, _L, _i, _o, _n, _END, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 900,
		.description = (const u8*) 0x8446f7c,
		.unusedDescription = (const u8*) 0x8446edc,
		.pokemonScale = 298,
		.pokemonOffset = 8,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_TOADYBLOYSTER] =
	{
		.categoryName = {_S, _e, _a, _SPACE, _L, _i, _o, _n, _END, _SPACE, _SPACE, _SPACE},
		.height = 17,
		.weight = 1200,
		.description = (const u8*) 0x8446ff3,
		.unusedDescription = (const u8*) 0x8446f3e,
		.pokemonScale = 288,
		.pokemonOffset = 1,
		.trainerScale = 306,
		.trainerOffset = 65535,
	},
	[NATIONAL_DEX_RANGINGBLOYSTER] =
	{
		.categoryName = {_S, _l, _u, _d, _g, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 9,
		.weight = 300,
		.description = (const u8*) 0x8447053,
		.unusedDescription = (const u8*) 0x8446fa7,
		.pokemonScale = 258,
		.pokemonOffset = 8,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SNOWYBLOWHOG] =
	{
		.categoryName = {_S, _l, _u, _d, _g, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 300,
		.description = (const u8*) 0x84470b7,
		.unusedDescription = (const u8*) 0x8447013,
		.pokemonScale = 288,
		.pokemonOffset = 7,
		.trainerScale = 288,
		.trainerOffset = 65535,
	},
	[NATIONAL_DEX_BLIZZARDINGBLOWHOG] =
	{
		.categoryName = {_B, _i, _v, _a, _l, _v, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 3,
		.weight = 40,
		.description = (const u8*) 0x8447123,
		.unusedDescription = (const u8*) 0x8447076,
		.pokemonScale = 643,
		.pokemonOffset = 21,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_GILDEMANDWEE] =
	{
		.categoryName = {_B, _i, _v, _a, _l, _v, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 15,
		.weight = 1325,
		.description = (const u8*) 0x8447186,
		.unusedDescription = (const u8*) 0x84470e9,
		.pokemonScale = 264,
		.pokemonOffset = 0,
		.trainerScale = 288,
		.trainerOffset = 65535,
	},
	[NATIONAL_DEX_GILDEMANDER] =
	{
		.categoryName = {_G, _a, _s, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 1,
		.description = (const u8*) 0x84471f9,
		.unusedDescription = (const u8*) 0x8447151,
		.pokemonScale = 256,
		.pokemonOffset = 0,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_WADDLEQUAFF] =
	{
		.categoryName = {_G, _a, _s, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 16,
		.weight = 1,
		.description = (const u8*) 0x8447265,
		.unusedDescription = (const u8*) 0x84471b1,
		.pokemonScale = 269,
		.pokemonOffset = 2,
		.trainerScale = 308,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_GRUBCHUCKER] =
	{
		.categoryName = {_S, _h, _a, _d, _o, _w, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 15,
		.weight = 405,
		.description = (const u8*) 0x84472c3,
		.unusedDescription = (const u8*) 0x844721e,
		.pokemonScale = 256,
		.pokemonOffset = 4,
		.trainerScale = 317,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_PEARLYCLAMCLAMP] =
	{
		.categoryName = {_R, _o, _c, _k, _SPACE, _S, _n, _a, _k, _e, _END, _SPACE},
		.height = 88,
		.weight = 2100,
		.description = (const u8*) 0x8447321,
		.unusedDescription = (const u8*) 0x8447281,
		.pokemonScale = 257,
		.pokemonOffset = 0,
		.trainerScale = 515,
		.trainerOffset = 12,
	},
	[NATIONAL_DEX_SUNQUISH] =
	{
		.categoryName = {_H, _y, _p, _n, _o, _s, _i, _s, _END, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 324,
		.description = (const u8*) 0x8447393,
		.unusedDescription = (const u8*) 0x84472ed,
		.pokemonScale = 274,
		.pokemonOffset = 7,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PROQUILLION] =
	{
		.categoryName = {_H, _y, _p, _n, _o, _s, _i, _s, _END, _SPACE, _SPACE, _SPACE},
		.height = 16,
		.weight = 756,
		.description = (const u8*) 0x84473f8,
		.unusedDescription = (const u8*) 0x8447352,
		.pokemonScale = 298,
		.pokemonOffset = 3,
		.trainerScale = 310,
		.trainerOffset = 2,
	},
	[NATIONAL_DEX_TUSKEDBLOWHOG] =
	{
		.categoryName = {_R, _i, _v, _e, _r, _SPACE, _C, _r, _a, _b, _END, _SPACE},
		.height = 4,
		.weight = 65,
		.description = (const u8*) 0x8447465,
		.unusedDescription = (const u8*) 0x84473b4,
		.pokemonScale = 469,
		.pokemonOffset = 18,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SNOWFLAKEFLUTTERTAIL] =
	{
		.categoryName = {_P, _i, _n, _c, _e, _r, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 600,
		.description = (const u8*) 0x84474c7,
		.unusedDescription = (const u8*) 0x844741d,
		.pokemonScale = 287,
		.pokemonOffset = 3,
		.trainerScale = 308,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_BOGSWALLOW] =
	{
		.categoryName = {_B, _a, _l, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 5,
		.weight = 104,
		.description = (const u8*) 0x8447532,
		.unusedDescription = (const u8*) 0x8447475,
		.pokemonScale = 364,
		.pokemonOffset = 65528,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PUFFMIN] =
	{
		.categoryName = {_B, _a, _l, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 666,
		.description = (const u8*) 0x844758a,
		.unusedDescription = (const u8*) 0x84474d9,
		.pokemonScale = 256,
		.pokemonOffset = 0,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_WOLLYHOP] =
	{
		.categoryName = {_E, _g, _g, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 4,
		.weight = 25,
		.description = (const u8*) 0x84475ee,
		.unusedDescription = (const u8*) 0x8447546,
		.pokemonScale = 495,
		.pokemonOffset = 65532,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CHILLYHOP] =
	{
		.categoryName = {_C, _o, _c, _o, _n, _u, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 20,
		.weight = 1200,
		.description = (const u8*) 0x844765b,
		.unusedDescription = (const u8*) 0x84475a5,
		.pokemonScale = 283,
		.pokemonOffset = 0,
		.trainerScale = 376,
		.trainerOffset = 7,
	},
	[NATIONAL_DEX_BLOOMCAPBLOYSTER] =
	{
		.categoryName = {_L, _o, _n, _e, _l, _y, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 4,
		.weight = 65,
		.description = (const u8*) 0x84476bf,
		.unusedDescription = (const u8*) 0x8447606,
		.pokemonScale = 545,
		.pokemonOffset = 19,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SCORCHCAKE] =
	{
		.categoryName = {_B, _o, _n, _e, _SPACE, _K, _e, _e, _p, _e, _r, _END},
		.height = 10,
		.weight = 450,
		.description = (const u8*) 0x8447727,
		.unusedDescription = (const u8*) 0x8447675,
		.pokemonScale = 293,
		.pokemonOffset = 12,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_WATERDUMPLE] =
	{
		.categoryName = {_K, _i, _c, _k, _i, _n, _g, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 15,
		.weight = 498,
		.description = (const u8*) 0x844778e,
		.unusedDescription = (const u8*) 0x84476d3,
		.pokemonScale = 256,
		.pokemonOffset = 0,
		.trainerScale = 273,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_LONGWATERDUMPLE] =
	{
		.categoryName = {_P, _u, _n, _c, _h, _i, _n, _g, _END, _SPACE, _SPACE, _SPACE},
		.height = 14,
		.weight = 502,
		.description = (const u8*) 0x84477f9,
		.unusedDescription = (const u8*) 0x8447733,
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 264,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MOCKIWI] =
	{
		.categoryName = {_L, _i, _c, _k, _i, _n, _g, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 655,
		.description = (const u8*) 0x8447865,
		.unusedDescription = (const u8*) 0x844779d,
		.pokemonScale = 272,
		.pokemonOffset = 3,
		.trainerScale = 272,
		.trainerOffset = 65533,
	},
	[NATIONAL_DEX_CRESTEDMOCKIWI] =
	{
		.categoryName = {_P, _o, _i, _s, _o, _n, _SPACE, _G, _a, _s, _END, _SPACE},
		.height = 6,
		.weight = 10,
		.description = (const u8*) 0x84478cf,
		.unusedDescription = (const u8*) 0x84477ff,
		.pokemonScale = 369,
		.pokemonOffset = 65535,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ELONGATEDCRUSHBLAT] =
	{
		.categoryName = {_P, _o, _i, _s, _o, _n, _SPACE, _G, _a, _s, _END, _SPACE},
		.height = 12,
		.weight = 95,
		.description = (const u8*) 0x844792d,
		.unusedDescription = (const u8*) 0x8447866,
		.pokemonScale = 321,
		.pokemonOffset = 65535,
		.trainerScale = 276,
		.trainerOffset = 65535,
	},
	[NATIONAL_DEX_PUFFSTALK] =
	{
		.categoryName = {_S, _p, _i, _k, _e, _s, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 1150,
		.description = (const u8*) 0x8447994,
		.unusedDescription = (const u8*) 0x84478cb,
		.pokemonScale = 291,
		.pokemonOffset = 7,
		.trainerScale = 276,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PUFFSTOOL] =
	{
		.categoryName = {_D, _r, _i, _l, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 19,
		.weight = 1200,
		.description = (const u8*) 0x84479f7,
		.unusedDescription = (const u8*) 0x844792e,
		.pokemonScale = 272,
		.pokemonOffset = 65535,
		.trainerScale = 344,
		.trainerOffset = 3,
	},
	[NATIONAL_DEX_ANODEBEETLE] =
	{
		.categoryName = {_E, _g, _g, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 346,
		.description = (const u8*) 0x8447a5f,
		.unusedDescription = (const u8*) 0x8447991,
		.pokemonScale = 257,
		.pokemonOffset = 6,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_EMPRESSBULBLAX] =
	{
		.categoryName = {_V, _i, _n, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 350,
		.description = (const u8*) 0x8447abf,
		.unusedDescription = (const u8*) 0x84479ef,
		.pokemonScale = 320,
		.pokemonOffset = 9,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SKEETERSKATE] =
	{
		.categoryName = {_P, _a, _r, _e, _n, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 22,
		.weight = 800,
		.description = (const u8*) 0x8447b28,
		.unusedDescription = (const u8*) 0x8447a5c,
		.pokemonScale = 257,
		.pokemonOffset = 65533,
		.trainerScale = 349,
		.trainerOffset = 5,
	},
	[NATIONAL_DEX_MUCKERSKATE] =
	{
		.categoryName = {_D, _r, _a, _g, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 4,
		.weight = 80,
		.description = (const u8*) 0x8447b90,
		.unusedDescription = (const u8*) 0x8447ac2,
		.pokemonScale = 399,
		.pokemonOffset = 65535,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_GROOVYLONGLEGS] =
	{
		.categoryName = {_D, _r, _a, _g, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 250,
		.description = (const u8*) 0x8447bf6,
		.unusedDescription = (const u8*) 0x8447b2b,
		.pokemonScale = 296,
		.pokemonOffset = 3,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CRUSTEDRUMPUP] =
	{
		.categoryName = {_G, _o, _l, _d, _f, _i, _s, _h, _END, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 150,
		.description = (const u8*) 0x8447c60,
		.unusedDescription = (const u8*) 0x8447b89,
		.pokemonScale = 379,
		.pokemonOffset = 4,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BEARDEDAMPRAT] =
	{
		.categoryName = {_G, _o, _l, _d, _f, _i, _s, _h, _END, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 390,
		.description = (const u8*) 0x8447cc9,
		.unusedDescription = (const u8*) 0x8447be5,
		.pokemonScale = 304,
		.pokemonOffset = 1,
		.trainerScale = 288,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_FIERYBULBLAX] =
	{
		.categoryName = {_S, _t, _a, _r, _SPACE, _S, _h, _a, _p, _e, _END, _SPACE},
		.height = 8,
		.weight = 345,
		.description = (const u8*) 0x8447d25,
		.unusedDescription = (const u8*) 0x8447c42,
		.pokemonScale = 326,
		.pokemonOffset = 1,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_GATTLINGGROINK] =
	{
		.categoryName = {_M, _y, _s, _t, _e, _r, _i, _o, _u, _s, _END, _SPACE},
		.height = 11,
		.weight = 800,
		.description = (const u8*) 0x8447d85,
		.unusedDescription = (const u8*) 0x8447cac,
		.pokemonScale = 301,
		.pokemonOffset = 3,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ARMURK] =
	{
		.categoryName = {_B, _a, _r, _r, _i, _e, _r, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 545,
		.description = (const u8*) 0x8447def,
		.unusedDescription = (const u8*) 0x8447d08,
		.pokemonScale = 258,
		.pokemonOffset = 4,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SEGMENTEDCRAWBSTER] =
	{
		.categoryName = {_M, _a, _n, _t, _i, _s, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 15,
		.weight = 560,
		.description = (const u8*) 0x8447e50,
		.unusedDescription = (const u8*) 0x8447d73,
		.pokemonScale = 272,
		.pokemonOffset = 0,
		.trainerScale = 293,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_ARMOREDMAWDAD] =
	{
		.categoryName = {_H, _u, _m, _a, _n, _SPACE, _S, _h, _a, _p, _e, _END},
		.height = 14,
		.weight = 406,
		.description = (const u8*) 0x8447eb4,
		.unusedDescription = (const u8*) 0x8447dd5,
		.pokemonScale = 256,
		.pokemonOffset = 3,
		.trainerScale = 300,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_SANDBELCKINGMEERSLUG] =
	{
		.categoryName = {_E, _l, _e, _c, _t, _r, _i, _c, _END, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 300,
		.description = (const u8*) 0x8447f1a,
		.unusedDescription = (const u8*) 0x8447e3b,
		.pokemonScale = 330,
		.pokemonOffset = 7,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CLICKINGSLURKER] =
	{
		.categoryName = {_S, _p, _i, _t, _f, _i, _r, _e, _END, _SPACE, _SPACE, _SPACE},
		.height = 13,
		.weight = 445,
		.description = (const u8*) 0x8447f80,
		.unusedDescription = (const u8*) 0x8447eae,
		.pokemonScale = 293,
		.pokemonOffset = 4,
		.trainerScale = 272,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_LURINGSLURKER] =
	{
		.categoryName = {_S, _t, _a, _g, _SPACE, _B, _e, _e, _t, _l, _e, _END},
		.height = 15,
		.weight = 550,
		.description = (const u8*) 0x8447fee,
		.unusedDescription = (const u8*) 0x8447f10,
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 257,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MEDUSALSLURKER] =
	{
		.categoryName = {_W, _i, _l, _d, _SPACE, _B, _u, _l, _l, _END, _SPACE, _SPACE},
		.height = 14,
		.weight = 884,
		.description = (const u8*) 0x844805a,
		.unusedDescription = (const u8*) 0x8447f79,
		.pokemonScale = 256,
		.pokemonOffset = 2,
		.trainerScale = 312,
		.trainerOffset = 3,
	},
	[NATIONAL_DEX_PELLETPOSY] =
	{
		.categoryName = {_F, _i, _s, _h, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 9,
		.weight = 100,
		.description = (const u8*) 0x84480af,
		.unusedDescription = (const u8*) 0x8447fd9,
		.pokemonScale = 317,
		.pokemonOffset = 4,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MASTERONION] =
	{
		.categoryName = {_A, _t, _r, _o, _c, _i, _o, _u, _s, _END, _SPACE, _SPACE},
		.height = 65,
		.weight = 2350,
		.description = (const u8*) 0x8448123,
		.unusedDescription = (const u8*) 0x8448032,
		.pokemonScale = 288,
		.pokemonOffset = 65535,
		.trainerScale = 512,
		.trainerOffset = 11,
	},
	[NATIONAL_DEX_OATCHI] =
	{
		.categoryName = {_T, _r, _a, _n, _s, _p, _o, _r, _t, _END, _SPACE, _SPACE},
		.height = 25,
		.weight = 2200,
		.description = (const u8*) 0x8448194,
		.unusedDescription = (const u8*) 0x8448098,
		.pokemonScale = 256,
		.pokemonOffset = 0,
		.trainerScale = 425,
		.trainerOffset = 8,
	},
	[NATIONAL_DEX_QUAGGLEDMIRECLOPS] =
	{
		.categoryName = {_T, _r, _a, _n, _s, _f, _o, _r, _m, _END, _SPACE, _SPACE},
		.height = 3,
		.weight = 40,
		.description = (const u8*) 0x84481f8,
		.unusedDescription = (const u8*) 0x84480fb,
		.pokemonScale = 602,
		.pokemonOffset = 21,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ALBINODWARFBULBORB] =
	{
		.categoryName = {_E, _v, _o, _l, _u, _t, _i, _o, _n, _END, _SPACE, _SPACE},
		.height = 3,
		.weight = 65,
		.description = (const u8*) 0x8448251,
		.unusedDescription = (const u8*) 0x844815a,
		.pokemonScale = 476,
		.pokemonOffset = 17,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_HAIRYBULBORB] =
	{
		.categoryName = {_B, _u, _b, _b, _l, _e, _SPACE, _J, _e, _t, _END, _SPACE},
		.height = 10,
		.weight = 290,
		.description = (const u8*) 0x84482b0,
		.unusedDescription = (const u8*) 0x84481cc,
		.pokemonScale = 316,
		.pokemonOffset = 7,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_WHIPTONGUEBULBORB] =
	{
		.categoryName = {_L, _i, _g, _h, _t, _n, _i, _n, _g, _END, _SPACE, _SPACE},
		.height = 8,
		.weight = 245,
		.description = (const u8*) 0x8448321,
		.unusedDescription = (const u8*) 0x844822b,
		.pokemonScale = 283,
		.pokemonOffset = 8,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ORANGEBULBORB] =
	{
		.categoryName = {_F, _l, _a, _m, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 9,
		.weight = 250,
		.description = (const u8*) 0x8448388,
		.unusedDescription = (const u8*) 0x844829f,
		.pokemonScale = 302,
		.pokemonOffset = 11,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_WHITEPIKMIN] =
	{
		.categoryName = {_V, _i, _r, _t, _u, _a, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 8,
		.weight = 365,
		.description = (const u8*) 0x84483fc,
		.unusedDescription = (const u8*) 0x844830b,
		.pokemonScale = 328,
		.pokemonOffset = 7,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BLUEPIKMIN] =
	{
		.categoryName = {_S, _p, _i, _r, _a, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 4,
		.weight = 75,
		.description = (const u8*) 0x8448468,
		.unusedDescription = (const u8*) 0x844836e,
		.pokemonScale = 521,
		.pokemonOffset = 20,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ROCKPIKMIN] =
	{
		.categoryName = {_S, _p, _i, _r, _a, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 10,
		.weight = 350,
		.description = (const u8*) 0x84484ce,
		.unusedDescription = (const u8*) 0x84483dd,
		.pokemonScale = 307,
		.pokemonOffset = 5,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_YELLOWPIKMIN] =
	{
		.categoryName = {_S, _h, _e, _l, _l, _f, _i, _s, _h, _END, _SPACE, _SPACE},
		.height = 5,
		.weight = 115,
		.description = (const u8*) 0x8448538,
		.unusedDescription = (const u8*) 0x8448444,
		.pokemonScale = 438,
		.pokemonOffset = 21,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_WINGEDPIKMIN] =
	{
		.categoryName = {_S, _h, _e, _l, _l, _f, _i, _s, _h, _END, _SPACE, _SPACE},
		.height = 13,
		.weight = 405,
		.description = (const u8*) 0x84485a4,
		.unusedDescription = (const u8*) 0x84484a9,
		.pokemonScale = 271,
		.pokemonOffset = 1,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_REDPIKMIN] =
	{
		.categoryName = {_F, _o, _s, _s, _i, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 18,
		.weight = 590,
		.description = (const u8*) 0x844860e,
		.unusedDescription = (const u8*) 0x8448510,
		.pokemonScale = 275,
		.pokemonOffset = 65535,
		.trainerScale = 317,
		.trainerOffset = 2,
	},
	[NATIONAL_DEX_PURPLEPIKMIN] =
	{
		.categoryName = {_S, _l, _e, _e, _p, _i, _n, _g, _END, _SPACE, _SPACE, _SPACE},
		.height = 21,
		.weight = 4600,
		.description = (const u8*) 0x844867e,
		.unusedDescription = (const u8*) 0x844857f,
		.pokemonScale = 275,
		.pokemonOffset = 1,
		.trainerScale = 408,
		.trainerOffset = 7,
	},
	[NATIONAL_DEX_WATERWRAITH] =
	{
		.categoryName = {_F, _r, _e, _e, _z, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 17,
		.weight = 554,
		.description = (const u8*) 0x84486f8,
		.unusedDescription = (const u8*) 0x84485e7,
		.pokemonScale = 278,
		.pokemonOffset = 0,
		.trainerScale = 308,
		.trainerOffset = 1,
	},
	[NATIONAL_DEX_TITANDWEEVIL] =
	{
		.categoryName = {_E, _l, _e, _c, _t, _r, _i, _c, _END, _SPACE, _SPACE, _SPACE},
		.height = 16,
		.weight = 526,
		.description = (const u8*) 0x8448760,
		.unusedDescription = (const u8*) 0x8448642,
		.pokemonScale = 275,
		.pokemonOffset = 1,
		.trainerScale = 330,
		.trainerOffset = 3,
	},
	[NATIONAL_DEX_PLASMWRAITH] =
	{
		.categoryName = {_F, _l, _a, _m, _e, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 20,
		.weight = 600,
		.description = (const u8*) 0x84487c0,
		.unusedDescription = (const u8*) 0x84486ab,
		.pokemonScale = 270,
		.pokemonOffset = 1,
		.trainerScale = 379,
		.trainerOffset = 6,
	},
	[NATIONAL_DEX_ICEPIKMIN] =
	{
		.categoryName = {_D, _r, _a, _g, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 18,
		.weight = 33,
		.description = (const u8*) 0x8448831,
		.unusedDescription = (const u8*) 0x844870a,
		.pokemonScale = 256,
		.pokemonOffset = 8,
		.trainerScale = 386,
		.trainerOffset = 6,
	},
	[NATIONAL_DEX_GLOWSEED] =
	{
		.categoryName = {_D, _r, _a, _g, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 40,
		.weight = 165,
		.description = (const u8*) 0x844888d,
		.unusedDescription = (const u8*) 0x844876e,
		.pokemonScale = 274,
		.pokemonOffset = 0,
		.trainerScale = 423,
		.trainerOffset = 6,
	},
	[NATIONAL_DEX_GLOWPIKMIN] =
	{
		.categoryName = {_D, _r, _a, _g, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 22,
		.weight = 2100,
		.description = (const u8*) 0x84488f7,
		.unusedDescription = (const u8*) 0x84487d5,
		.pokemonScale = 283,
		.pokemonOffset = 65535,
		.trainerScale = 342,
		.trainerOffset = 4,
	},
	[NATIONAL_DEX_SMOKYPROGG] =
	{
		.categoryName = {_G, _e, _n, _e, _t, _i, _c, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 20,
		.weight = 1220,
		.description = (const u8*) 0x8448952,
		.unusedDescription = (const u8*) 0x844883a,
		.pokemonScale = 276,
		.pokemonOffset = 65535,
		.trainerScale = 342,
		.trainerOffset = 5,
	},
	[NATIONAL_DEX_MAMUTA] =
	{
		.categoryName = {_N, _e, _w, _SPACE, _S, _p, _e, _c, _i, _e, _s, _END},
		.height = 4,
		.weight = 40,
		.description = (const u8*) 0x84489b7,
		.unusedDescription = (const u8*) 0x844889d,
		.pokemonScale = 460,
		.pokemonOffset = 65534,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MOSS] =
	{
		.categoryName = {_L, _e, _a, _f, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 9,
		.weight = 64,
		.description = (const u8*) 0x8448a26,
		.unusedDescription = (const u8*) 0x8448906,
		.pokemonScale = 512,
		.pokemonOffset = 18,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_TOYBORB] =
	{
		.categoryName = {_L, _e, _a, _f, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 158,
		.description = (const u8*) 0x8448a7e,
		.unusedDescription = (const u8*) 0x8448965,
		.pokemonScale = 296,
		.pokemonOffset = 4,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BULBLORD] =
	{
		.categoryName = {_H, _e, _r, _b, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 18,
		.weight = 1005,
		.description = (const u8*) 0x8448add,
		.unusedDescription = (const u8*) 0x84489c7,
		.pokemonScale = 286,
		.pokemonOffset = 0,
		.trainerScale = 317,
		.trainerOffset = 2,
	},
	[NATIONAL_DEX_PINCHIPEDE] =
	{
		.categoryName = {_F, _i, _r, _e, _SPACE, _M, _o, _u, _s, _e, _END, _SPACE},
		.height = 5,
		.weight = 79,
		.description = (const u8*) 0x8448b3f,
		.unusedDescription = (const u8*) 0x8448a2e,
		.pokemonScale = 539,
		.pokemonOffset = 19,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_LARGEMOUTHWOLLYHOP] =
	{
		.categoryName = {_V, _o, _l, _c, _a, _n, _o, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 9,
		.weight = 190,
		.description = (const u8*) 0x8448b9e,
		.unusedDescription = (const u8*) 0x8448a90,
		.pokemonScale = 329,
		.pokemonOffset = 10,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_TOYBLOWHOG] =
	{
		.categoryName = {_V, _o, _l, _c, _a, _n, _o, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 17,
		.weight = 795,
		.description = (const u8*) 0x8448bfc,
		.unusedDescription = (const u8*) 0x8448af4,
		.pokemonScale = 284,
		.pokemonOffset = 65535,
		.trainerScale = 287,
		.trainerOffset = 0,
	},
	[NATIONAL_DEX_TELESCOPINGPUMPHOG] =
	{
		.categoryName = {_B, _i, _g, _SPACE, _J, _a, _w, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 95,
		.description = (const u8*) 0x8448c5b,
		.unusedDescription = (const u8*) 0x8448b59,
		.pokemonScale = 487,
		.pokemonOffset = 20,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BEEB] =
	{
		.categoryName = {_B, _i, _g, _SPACE, _J, _a, _w, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 250,
		.description = (const u8*) 0x8448cba,
		.unusedDescription = (const u8*) 0x8448bbd,
		.pokemonScale = 378,
		.pokemonOffset = 11,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BLADEDBEED] =
	{
		.categoryName = {_B, _i, _g, _SPACE, _J, _a, _w, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 23,
		.weight = 888,
		.description = (const u8*) 0x8448d1e,
		.unusedDescription = (const u8*) 0x8448c24,
		.pokemonScale = 282,
		.pokemonOffset = 65535,
		.trainerScale = 375,
		.trainerOffset = 6,
	},
	[NATIONAL_DEX_STUDDEDBEEB] =
	{
		.categoryName = {_S, _c, _o, _u, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 8,
		.weight = 60,
		.description = (const u8*) 0x8448d8a,
		.unusedDescription = (const u8*) 0x8448c8d,
		.pokemonScale = 439,
		.pokemonOffset = 12,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_FIREFLAPBULBORB] =
	{
		.categoryName = {_L, _o, _n, _g, _SPACE, _B, _o, _d, _y, _END, _SPACE, _SPACE},
		.height = 18,
		.weight = 325,
		.description = (const u8*) 0x8448df3,
		.unusedDescription = (const u8*) 0x8448cfa,
		.pokemonScale = 346,
		.pokemonOffset = 10,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ICEBLOWNDWEEVIL] =
	{
		.categoryName = {_O, _w, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 7,
		.weight = 212,
		.description = (const u8*) 0x8448e57,
		.unusedDescription = (const u8*) 0x8448d64,
		.pokemonScale = 380,
		.pokemonOffset = 15,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SPECTRALID] =
	{
		.categoryName = {_O, _w, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 16,
		.weight = 408,
		.description = (const u8*) 0x8448ec1,
		.unusedDescription = (const u8*) 0x8448dc0,
		.pokemonScale = 278,
		.pokemonOffset = 2,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BLUBBUG] =
	{
		.categoryName = {_F, _i, _v, _e, _SPACE, _S, _t, _a, _r, _END, _SPACE, _SPACE},
		.height = 10,
		.weight = 108,
		.description = (const u8*) 0x8448f1d,
		.unusedDescription = (const u8*) 0x8448e27,
		.pokemonScale = 256,
		.pokemonOffset = 4,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PUFFYBLUBBUG] =
	{
		.categoryName = {_F, _i, _v, _e, _SPACE, _S, _t, _a, _r, _END, _SPACE, _SPACE},
		.height = 14,
		.weight = 356,
		.description = (const u8*) 0x8448f87,
		.unusedDescription = (const u8*) 0x8448e8c,
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_STUFFEDBELLBLOOM] =
	{
		.categoryName = {_S, _t, _r, _i, _n, _g, _SPACE, _S, _p, _i, _t, _END},
		.height = 5,
		.weight = 85,
		.description = (const u8*) 0x8448ff0,
		.unusedDescription = (const u8*) 0x8448ef4,
		.pokemonScale = 414,
		.pokemonOffset = 20,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CENTIPARE] =
	{
		.categoryName = {_L, _o, _n, _g, _SPACE, _L, _e, _g, _END, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 335,
		.description = (const u8*) 0x8449052,
		.unusedDescription = (const u8*) 0x8448f5c,
		.pokemonScale = 316,
		.pokemonOffset = 7,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ADULTCENTIPARE] =
	{
		.categoryName = {_B, _a, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 18,
		.weight = 750,
		.description = (const u8*) 0x84490bd,
		.unusedDescription = (const u8*) 0x8448fca,
		.pokemonScale = 279,
		.pokemonOffset = 65535,
		.trainerScale = 313,
		.trainerOffset = 2,
	},
	[NATIONAL_DEX_WATERYBLOWHOG] =
	{
		.categoryName = {_A, _n, _g, _l, _e, _r, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 5,
		.weight = 120,
		.description = (const u8*) 0x8449124,
		.unusedDescription = (const u8*) 0x8449032,
		.pokemonScale = 424,
		.pokemonOffset = 65534,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_GRABBIT] =
	{
		.categoryName = {_L, _i, _g, _h, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 12,
		.weight = 225,
		.description = (const u8*) 0x8449181,
		.unusedDescription = (const u8*) 0x8449097,
		.pokemonScale = 269,
		.pokemonOffset = 6,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_COPPELLER] =
	{
		.categoryName = {_T, _i, _n, _y, _SPACE, _M, _o, _u, _s, _e, _END, _SPACE},
		.height = 3,
		.weight = 20,
		.description = (const u8*) 0x84491e6,
		.unusedDescription = (const u8*) 0x8449100,
		.pokemonScale = 508,
		.pokemonOffset = 17,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_MUGGONFLY] =
	{
		.categoryName = {_S, _t, _a, _r, _SPACE, _S, _h, _a, _p, _e, _END, _SPACE},
		.height = 3,
		.weight = 30,
		.description = (const u8*) 0x844924f,
		.unusedDescription = (const u8*) 0x8449159,
		.pokemonScale = 462,
		.pokemonOffset = 22,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ELECTRICCOTTONADE] =
	{
		.categoryName = {_B, _a, _l, _l, _o, _o, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 3,
		.weight = 10,
		.description = (const u8*) 0x84492a8,
		.unusedDescription = (const u8*) 0x84491b3,
		.pokemonScale = 457,
		.pokemonOffset = 65535,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_WADDLEPUS] =
	{
		.categoryName = {_S, _p, _i, _k, _e, _SPACE, _B, _a, _l, _l, _END, _SPACE},
		.height = 3,
		.weight = 15,
		.description = (const u8*) 0x8449302,
		.unusedDescription = (const u8*) 0x8449211,
		.pokemonScale = 507,
		.pokemonOffset = 21,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CRAMMEDWRAITH] =
	{
		.categoryName = {_H, _a, _p, _p, _i, _n, _e, _s, _s, _END, _SPACE, _SPACE},
		.height = 6,
		.weight = 32,
		.description = (const u8*) 0x8449360,
		.unusedDescription = (const u8*) 0x8449276,
		.pokemonScale = 424,
		.pokemonOffset = 15,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BERSERKLEECHHYDROE] =
	{
		.categoryName = {_T, _i, _n, _y, _SPACE, _B, _i, _r, _d, _END, _SPACE, _SPACE},
		.height = 2,
		.weight = 20,
		.description = (const u8*) 0x84493c5,
		.unusedDescription = (const u8*) 0x84492e1,
		.pokemonScale = 610,
		.pokemonOffset = 23,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PEBBLEPITCHER] =
	{
		.categoryName = {_M, _y, _s, _t, _i, _c, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 15,
		.weight = 150,
		.description = (const u8*) 0x8449431,
		.unusedDescription = (const u8*) 0x8449349,
		.pokemonScale = 258,
		.pokemonOffset = 4,
		.trainerScale = 317,
		.trainerOffset = 3,
	},
	[NATIONAL_DEX_ANCIENTSIREHOUND] =
	{
		.categoryName = {_W, _o, _o, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 6,
		.weight = 78,
		.description = (const u8*) 0x8449493,
		.unusedDescription = (const u8*) 0x84493ae,
		.pokemonScale = 379,
		.pokemonOffset = 18,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_COURAGEREACTOR] =
	{
		.categoryName = {_W, _o, _o, _l, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 8,
		.weight = 133,
		.description = (const u8*) 0x84494f8,
		.unusedDescription = (const u8*) 0x844941a,
		.pokemonScale = 372,
		.pokemonOffset = 13,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_ASSEMBLEDCOURAGE] =
	{
		.categoryName = {_L, _i, _g, _h, _t, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 14,
		.weight = 1000,
		.description = (const u8*) 0x8449559,
		.unusedDescription = (const u8*) 0x8449486,
		.pokemonScale = 275,
		.pokemonOffset = 2,
		.trainerScale = 283,
		.trainerOffset = 65535,
	},
	[NATIONAL_DEX_REMEMBEREDOLDBUDDY] =
	{
		.categoryName = {_F, _l, _o, _w, _e, _r, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 4,
		.weight = 58,
		.description = (const u8*) 0x84495c4,
		.unusedDescription = (const u8*) 0x84494f7,
		.pokemonScale = 472,
		.pokemonOffset = 19,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_BULBORBWITHAGUN] =
	{
		.categoryName = {_A, _q, _u, _a, _SPACE, _M, _o, _u, _s, _e, _END, _SPACE},
		.height = 4,
		.weight = 85,
		.description = (const u8*) 0x844962a,
		.unusedDescription = (const u8*) 0x8449556,
		.pokemonScale = 476,
		.pokemonOffset = 19,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_KIRBY] =
	{
		.categoryName = {_A, _q, _u, _a, _SPACE, _R, _a, _b, _b, _i, _t, _END},
		.height = 8,
		.weight = 285,
		.description = (const u8*) 0x8449688,
		.unusedDescription = (const u8*) 0x84495b9,
		.pokemonScale = 448,
		.pokemonOffset = 15,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_SOUL] =
	{
		.categoryName = {_I, _m, _i, _t, _a, _t, _i, _o, _n, _END, _SPACE, _SPACE},
		.height = 12,
		.weight = 380,
		.description = (const u8*) 0x84496eb,
		.unusedDescription = (const u8*) 0x8449624,
		.pokemonScale = 305,
		.pokemonOffset = 7,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PLACEHOLDERLARVA] =
	{
		.categoryName = {_F, _r, _o, _g, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 11,
		.weight = 339,
		.description = (const u8*) 0x8449756,
		.unusedDescription = (const u8*) 0x8449681,
		.pokemonScale = 289,
		.pokemonOffset = 5,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_DEMO77] =
	{
		.categoryName = {_C, _o, _t, _t, _o, _n, _w, _e, _e, _d, _END, _SPACE},
		.height = 4,
		.weight = 5,
		.description = (const u8*) 0x84497bb,
		.unusedDescription = (const u8*) 0x84496e4,
		.pokemonScale = 562,
		.pokemonOffset = 65529,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_USUBA] =
	{
		.categoryName = {_C, _o, _t, _t, _o, _n, _w, _e, _e, _d, _END, _SPACE},
		.height = 6,
		.weight = 10,
		.description = (const u8*) 0x844981e,
		.unusedDescription = (const u8*) 0x8449745,
		.pokemonScale = 387,
		.pokemonOffset = 0,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_KAKUREIMO] =
	{
		.categoryName = {_C, _o, _t, _t, _o, _n, _w, _e, _e, _d, _END, _SPACE},
		.height = 8,
		.weight = 30,
		.description = (const u8*) 0x844987d,
		.unusedDescription = (const u8*) 0x84497b1,
		.pokemonScale = 418,
		.pokemonOffset = 65532,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_PIKUTABE] =
	{
		.categoryName = {_L, _o, _n, _g, _SPACE, _T, _a, _i, _l, _END, _SPACE, _SPACE},
		.height = 8,
		.weight = 115,
		.description = (const u8*) 0x84498e9,
		.unusedDescription = (const u8*) 0x8449816,
		.pokemonScale = 363,
		.pokemonOffset = 8,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_NAMAPONGASHI] =
	{
		.categoryName = {_S, _e, _e, _d, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 3,
		.weight = 18,
		.description = (const u8*) 0x844994d,
		.unusedDescription = (const u8*) 0x8449881,
		.pokemonScale = 541,
		.pokemonOffset = 0,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
	[NATIONAL_DEX_CHAPPYPROTO] =
	{
		.categoryName = {_S, _u, _n, _END, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE, _SPACE},
		.height = 8,
		.weight = 85,
		.description = (const u8*) 0x84499b8,
		.unusedDescription = (const u8*) 0x84498e9,
		.pokemonScale = 374,
		.pokemonOffset = 12,
		.trainerScale = 256,
		.trainerOffset = 65534,
	},
};
